# Generated by Django 4.1 on 2022-08-23 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('password', models.CharField(default='', max_length=255, unique=True)),
                ('tries', models.IntegerField(default=3)),
                ('blocked', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('twoFactorAuth', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TwoFactorAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, unique=True)),
                ('expirationDate', models.DateTimeField(default=datetime.datetime(2022, 8, 23, 17, 40, 7, 971736, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, unique=True)),
                ('expirationDate', models.DateTimeField(default=datetime.datetime(2022, 8, 23, 17, 40, 7, 970793, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, unique=True)),
                ('expirationDate', models.DateTimeField(default=datetime.datetime(2022, 8, 23, 17, 40, 7, 969244, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user')),
            ],
        ),
    ]
