# Generated by Django 4.1 on 2022-08-26 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserManagement.user')),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('profileId', models.CharField(default='', max_length=255, unique=True)),
            ],
            bases=('UserManagement.user', models.Model),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 21, 24, 6, 594313, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 21, 24, 6, 594677, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='twofactorauthcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 21, 24, 6, 595051, tzinfo=datetime.timezone.utc)),
        ),
    ]
