# Generated by Django 4.1 on 2022-08-27 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_facebookuser_alter_confirmationcode_expirationdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookuser',
            name='name',
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='picture',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 18, 12, 57, 97683, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 18, 12, 57, 98059, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='twofactorauthcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 18, 12, 57, 98432, tzinfo=datetime.timezone.utc)),
        ),
    ]
