# Generated by Django 4.1 on 2022-08-23 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_token_alter_confirmationcode_expirationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 19, 44, 25, 893273, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 19, 44, 25, 893662, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='twofactorauthcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 19, 44, 25, 894012, tzinfo=datetime.timezone.utc)),
        ),
    ]
