# Generated by Django 4.1 on 2022-08-27 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_alter_confirmationcode_expirationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericuser',
            name='salt',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 22, 17, 55, 805687, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 22, 17, 55, 806418, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='twofactorauthcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 22, 17, 55, 806954, tzinfo=datetime.timezone.utc)),
        ),
    ]
