# Generated by Django 4.0.4 on 2022-06-24 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_confirmationcode_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='expirationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
