# Generated by Django 4.0.5 on 2022-06-25 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_alter_confirmationcode_expirationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='tries',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 12, 26, 44, 195571, tzinfo=utc)),
        ),
    ]
