# Generated by Django 4.0.5 on 2022-06-25 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0009_confirmationcode_tries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationcode',
            name='tries',
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 18, 24, 53, 553977, tzinfo=utc)),
        ),
    ]
