# Generated by Django 4.0.5 on 2022-06-29 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0011_alter_confirmationcode_expirationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twoFactorAuth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 11, 29, 58, 774073, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 11, 29, 58, 774584, tzinfo=utc)),
        ),
    ]
